### ISSUE TITLE
ACS-74 stealth cloak not granting invisibility

### ISSUE THREAD

**Issue by Noxious-Stimuli** [Noctifer-de-Mortem/nocts_cata_mod#463]
Something between experimental 2022-12-08-2207 and experimental 2022-12-09-0649 has broken the ACS-74, it no longer grants the "Invisible" condition and NPCs/monsters can quite happily see my character.

Not sure if this is related, but the stock DDA item the RM UPS stealth cloak now specifically states that it grants "Invisibility" as an effect when powered by UPS. Might be faulty memory but I don't remember it stating that before.

**Comment by Noxious-Stimuli** [comment]
Slight correction, it should be experimental 2022-12-08-1147, not 2022-12-08-2207.

**Comment by chaosvolt** [comment]
Update the mod as well, reminder to do it manually and do not use the launcher. This should have been fixed in: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/462

**Comment by Noxious-Stimuli** [comment]
Redownloaded as per the experimental instructions, by downloading the main branch and deleting the old folder and copying nocts_cata_mod_DDA over.

Issue persists on my old save/world, but *not* on a freshly created one.

**Comment by chaosvolt** [comment]
Ah, that would mean the fix worked but old versions of the item in old saves still have the old relic data that didn't work right. The stealth cloak relies on relic data, which is saved per item.

**Comment by chaosvolt** [comment]
Hmm, odd. :/
